require("config.plugins.treesitter")
require("config.plugins.telescope")
require("config.plugins.miniclue")
require("config.plugins.codecompanion")
require("config.plugins.tjlang").setup()
require("config.plugins.asm").setup()
