require("config.appearence")
require("config.crates")
require("config.hipatterns")
require("config.icon_picker")
require("config.luasnip")
require("config.mason")
require("config.comment")
require("config.nvim_autopairs")
require("config.nvim_cmp")
require("config.nvim_tmux")
require("config.nvim_tree")
require("config.telescope")
require("config.treesitter")
require("config.trouble")
require("config.urlview")

-- vim:foldmethod=marker foldlevel=0
