"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
[character]
success_symbol = "[❯](bold bright-green)"
format = "$sudo$symbol$shell "
error_symbol = "[✗](red bold)"
vicmd_symbol = "[](bold green)"
[python]
symbol = "[ ](bold yellow)"
[lua]
symbol = "[ ](bold blue)"
[rust]
symbol = "[ ](bold red)"
[package] 
symbol = "[ ](bold 208)"

