#!/usr/bin/bash
unset CDPATH
mkdir $HOME/Cpp/
cd $HOME/Cpp
gh repo clone Utils
cd ~
gh repo clone Rust
gh repo clone timelog

case $1 in
-n)
  echo "Copying files... This may take a while"
  sudo mkdir /root/.config/nvim /root/.local/share/nvim -p
  sudo cp ~/.config/nvim/* -r /root/.config/nvim
  sudo cp ~/.local/share/nvim/* -r /root/.local/share/nvim
  ;;
esac

if [ "$1" != "-g" ]; then
  ./gitConfig
fi
