#!/bin/bash
git config --global user.email 91501317+Monster0506@users.noreply.github.com
git config --global user.name monster0506
git config --global alias.unstage "reset HEAD --"
git config --global alias.k "!gitk"
git config --global alias.last "log -1 HEAD --stat"
git config --global alias.save "!git add -A && git commit -m 'chore: commit save point -- -'"
git config --global alias.ll 'log --pretty=format:"%C(yellow)%h%Cred%d\\ %Creset%s%Cblue\\ [%cn]" --decorate'
git config --global alias.ls 'log --pretty=format:"%C(yellow)%h%Cred%d\\ %Creset%s%Cblue\\ [%cn]" --decorate --numstat'
git config --global alias.s 'status'
git config --global alias.sta 'status'
git config --global core.editor "nvim"
git config --global core.excludesfile $HOME/.gitignore_global
